name: Checks

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]
  merge_group:
  workflow_run:
    workflows: ["Update rust-overlay"]
    branches:
      - 'rust-overlay'
    types:
      - completed

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - base
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses:  DeterminateSystems/magic-nix-cache-action@v6
      - name: Run checks
        run: nix build .#checks.x86_64-linux.${{ matrix.rust }}
